import unittest

# Pentagonal Puzzle
""" 

Pentagonal numbers are generated by the formula: $P_n = \tfrac 12n(3n-1)$ giving the sequence:


Some pentagonal numbers can be expressed as the sum of two other pentagonal numbers.
For example:


3577 is the smallest pentagonal number that can be expressed as the sum of two pentagonal numbers in two different ways


107602 is the smallest pentagonal number that can be expressed as the sum of two pentagonal numbers in three different ways.


Find the smallest pentagonal number that can be expressed as the sum of two pentagonal numbers in over 100 different ways.

""" 


class Test(unittest.TestCase):
    def test(self):
        pass
