import unittest

# Pythagorean tree
""" 

The Pythagorean tree is a fractal generated by the following procedure:


Start with a unit square. Then, calling one of the sides its base (in the animation, the bottom side is the base):


It can be shown that there exists at least one rectangle, whose sides are parallel to the largest square of the Pythagorean tree, which encloses the Pythagorean tree completely.


Find the smallest area possible for such a bounding rectangle, and give your answer rounded to 10 decimal places.

""" 


class Test(unittest.TestCase):
    def test(self):
        pass
